### ISSUE TITLE
why getProperty not returns only property  ?

### ISSUE THREAD

**Issue by mortenko** [akamai/AkamaiOPEN-edgegrid-golang#148]
I'm really curious why getProperty func from property.go  does not return only Property struct but also Response and allProperties.

It does not make any sense ...look here [getPropertyResponse](https://github.com/akamai/AkamaiOPEN-edgegrid-golang/blob/5bf72bbd23d4bfe8fcec060cb2962f7da96a9247/pkg/papi/property.go#L94)

**Comment by robertolopezlopez** [comment]
PAPI was the first Akamai API which the current team covered and there are more than 1 single piece of code which make us wonder today "why we wrote it that way".

This quirk was implemented (I guess - I cannot really remember), because of the way this endpoint is implemented. Get property returns a list of properties which match the given ID, not just one. Thus the person who implemented thought that it would be a good idea to return not just the list of properties returned but also the first of those. In practice, there are just zero or one property matching each property ID.

https://techdocs.akamai.com/property-mgr/reference/get-property

If you consider that you may be able to craft a better solution, please feel free to create a PR :-)
