### ISSUE TITLE
Unable to edit read-only element 

### ISSUE THREAD

**Issue by vivekdasgupta** [akamai/AkamaiOPEN-edgegrid-golang#23]
Hi,

I am using this library to update rule tree using PAPI API.  Creating a new property version works fine.  However when updating a rule criteria the Luna API server returns this error : 

 "type" : "https://problems.luna.akamaiapis.net/papi/v0/property-version/lock-error",
  "title" : "Unable to edit read-only element",
  "status" : 403,
  "detail" : "Only Akamai representatives can change read-only behaviors, criteria and child rules.",

I am using the PUT example.  Does client.NewJSONRequest()  expect a JSON object in the "body", or just passing a struct is ok ?

Vivek

**Comment by dshafik** [comment]
@vivekdasgupta to answer your second question first: yes, passing a struct to `client.NewJSONRequest()` is correct, it will be passed through to the standard `json.Marshal()`.

Regarding the error you are getting, it is due to a read-only or locked rule/behavior/criteria in the rule tree… would you be able to fetch the rules JSON (see: [this](https://developer.akamai.com/api/luna/papi/resources.html#getpropertyversionrules)) and look for any of the following in your rules/behavior/criteria:

- `uuid` key/value
- `locked` key with a `true` value
- `criteriaLocked` key with a `true` value

And then share just the specific rule/behavior/criteria here so I can test? If you prefer, send me the entire rules JSON to dshafik@akamai.com

Thanks!

**Comment by vivekdasgupta** [comment]
Hi Davey  ( @dshafik ) ,
Thanks for the response.  I have sent you the rules json, the current PUT request body and the code which I am using now. Also attached the current error.

Earlier I was trying to put the entire rules in the PUT body. But now I am only keeping the minimal modified rules/data, in the PUT body.  Still similar error.  Most likely its due to uuid and/or advanced behaviour.    But I notice that there is no uuid nor any advanced behaviour in the part that I am trying to modify.

Is it sufficient to supply only the modified data in the PUT body ?

**Comment by dshafik** [comment]
@vivekdasgupta unfortunately, due to the nature of the API, we don't yet support `PATCH`-like capabilities, you will need to supply the entire rule set.

I believe the issue here is a mis-match between the data-structures we Unmarshal into, vs those sent from the API, so we're losing the UUID or locked data.

**Comment by vivekdasgupta** [comment]
Yes earlier I was unmarshaling into papi.Rules and I noticed that there were some fields missing.  Now I unmarshal into a custom struct as per the JSON response. And this works for me.

type OptionValue map[string]interface{}
type AkamaiPropertyRules struct {
	AccountID       string `json:"accountId"`
	ContractID      string `json:"contractId"`
	GroupID         string `json:"groupId"`
	PropertyID      string `json:"propertyId"`
	PropertyName    string `json:"propertyName"`
	PropertyVersion int    `json:"propertyVersion"`
	Etag            string `json:"etag"`
	Rules           struct {
		Name     string `json:"name"`
		Children []struct {
			Name      string        `json:"name"`
			Children  []interface{} `json:"children"`
			Behaviors []struct {
				Name    string      `json:"name"`
				Options OptionValue `json:"options"`
			} `json:"behaviors"`
			Criteria []struct {
				Name    string      `json:"name"`
				Options OptionValue `json:"options"`
			} `json:"criteria"`
			CriteriaMustSatisfy string `json:"criteriaMustSatisfy"`
			Comments            string `json:"comments,omitempty"`
			UUID                string `json:"uuid,omitempty"`
			TemplateLink        string `json:"templateLink,omitempty"`
		} `json:"children"`
		Behaviors []struct {
			Name    string      `json:"name"`
			Options OptionValue `json:"options"`
		} `json:"behaviors"`
		UUID    string `json:"uuid"`
		Options struct {
			IsSecure bool `json:"is_secure"`
		} `json:"options"`
		Variables []struct {
			Name        string `json:"name"`
			Value       string `json:"value"`
			Description string `json:"description"`
			Hidden      bool   `json:"hidden"`
			Sensitive   bool   `json:"sensitive"`
		} `json:"variables"`
		Comments string `json:"comments"`
	} `json:"rules"`
	Warnings []struct {
		Type                string `json:"type"`
		ErrorLocation       string `json:"errorLocation,omitempty"`
		Detail              string `json:"detail"`
		Title               string `json:"title,omitempty"`
		CurrentRuleFormat   string `json:"currentRuleFormat,omitempty"`
		SuggestedRuleFormat string `json:"suggestedRuleFormat,omitempty"`
	} `json:"warnings"`
	RuleFormat string `json:"ruleFormat"`
}

Thanks for the help.

**Comment by dshafik** [comment]
@vivekdasgupta I have merged in changes which should bring full parity with the changes in PAPI v1, including these missing fields. This should correctly solve your problem.
